# === PENGATURAN DASAR (ROOT) ===
baseURL = "https://musnotess.vercel.app/"
languageCode = "id"
title = "MuS"          # Ini yang bakal ngubah teks di pojok kiri atas!
theme = "PaperMod"     # Penting biar temanya kebaca
enableRobotsTXT = true

# === PENGATURAN TEMA (PARAMS) ===
[params]
    env = "production"
    description = "Catatan reflektif tentang biologi dan sistem."

    defaultTheme = "auto"
    disableThemeToggle = false

    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = false
    ShowToc = false
    ShowWordCount = false
    ShowFullTextinRSS = true

    ShowCodeCopyButtons = false
    disableScrollToTop = false

    # --- DASHBOARD (PROFILE MODE) ---
    [params.profileMode]
        enabled = true
        title = "MuS"
        subtitle = "Kumpulan hipotesis mentah tentang biologi dan sistem. Saya lebih sering bingung daripada tahu."
        imageUrl = "https://github.com/Musae18.png"
        imageTitle = "MuS"
        imageWidth = 120
        imageHeight = 120
        imageBorder = false

        [[params.profileMode.buttons]]
            name = "Catatan Keraguan"
            url = "posts"

        [[params.profileMode.buttons]]
            name = "Aktualisasi lain"
            url = "projects"


    # --- IKON SOSIAL MEDIA ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Musae18"
[params.assets]
        favicon = "favicon.ico"
